# Generated by Django 4.0.2 on 2022-02-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_funcionario_email_funcionario_sobrenome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto_funcionatio',
            field=models.ImageField(default=1, upload_to=models.CharField(help_text='Nome do funcionário', max_length=100)),
            preserve_default=False,
        ),
    ]
