# Generated by Django 4.0.4 on 2022-07-20 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_alter_funcionario_foto_funcionatio'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='funcionario_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
