# Generated by Django 4.0.4 on 2022-07-20 23:34

from django.db import migrations, models
import funcionarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0012_funcionario_atualizado_em_funcionario_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto_funcionatio',
            field=models.ImageField(blank=True, default='usuario.png', null=True, upload_to=funcionarios.models.upload_to),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcionario_code',
            field=models.CharField(blank=True, default=funcionarios.models.gerar_id, help_text='ID identificador QR code', max_length=14, null=True, unique=True),
        ),
    ]
