# Generated by Django 4.0.4 on 2022-07-21 19:09

from django.db import migrations, models
import django.utils.timezone
import ponto_qrcode.models.ponto_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PontosQrCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
                ('dia', models.CharField(blank=True, default=ponto_qrcode.models.ponto_model.data_atual, max_length=20, null=True)),
                ('hora_do_ponto', models.DateTimeField(blank=True, null=True, verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
