# Generated by Django 4.0.4 on 2022-11-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosqrcodemodel',
            name='hora_do_ponto',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
