# Generated by Django 3.2.11 on 2022-01-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Nome do documento', max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='Documentos',
        ),
    ]
