# Generated by Django 3.2.11 on 2022-01-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20220119_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descricao',
            field=models.CharField(help_text='Descrição do documento', max_length=70),
        ),
    ]
