# Generated by Django 3.2.11 on 2022-01-19 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_rename_funcionarios_funcionario'),
        ('documentos', '0003_alter_documento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='proprietario_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
    ]
