# Generated by Django 3.2.11 on 2022-01-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hora_Extra',
            new_name='HoraExtra',
        ),
    ]
