# Generated by Django 3.2.11 on 2022-01-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0002_rename_hora_extra_horaextra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HoraExtra',
            new_name='RegistroHoraExtra',
        ),
    ]
