# Generated by Django 3.2.11 on 2022-01-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0003_rename_horaextra_registrohoraextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohoraextra',
            name='nome',
        ),
        migrations.AddField(
            model_name='registrohoraextra',
            name='motivo',
            field=models.CharField(default=1, help_text='Motivo da Hora Extra', max_length=70),
            preserve_default=False,
        ),
    ]
